[tox]
envlist =
    py{39,310,311,312,313,314}

[testenv]
usedevelop = true
extras = tests
setenv =
    ASGI_THREADS = 4
    COVERAGE_PROCESS_START = {toxinidir}/pyproject.toml
commands =
    pytest -v --cov=daphne --cov-report=term-missing --cov-report=html:reports/coverage_html_report {posargs}
